![image](https://user-images.githubusercontent.com/10642660/80533917-5abc8900-896c-11ea-86ac-7f8fb72e5942.png)
title: Bryce Quillin
description: Economist & computational social scientist
google_analytics: 
show_downloads: true
theme: jekyll-theme-dinky

